---
- hosts: leaf1-DC1
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DC1.yml"
      name: underlay
  - name: Test variables
    debug:
      msg: "{{ underlay }}"
  - name: Create a configuration for Ethernet3
    template:
      src: "{{lookup('env','PWD')}}/templates/interfaces_ebgp.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_underlay.cfg"
  - name: Upload config to switch
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_underlay.cfg"


